apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oneuptime-encryption
  namespace: oneuptime
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oneuptime-encryption
    creationPolicy: Owner
  data:
    - secretKey: encryptionKey
      remoteRef:
        key: secret/oneuptime/encryption
        property: encryptionKey
    - secretKey: jwtSecret
      remoteRef:
        key: secret/oneuptime/encryption
        property: jwtSecret
